services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    RM\Standard\Message\Format\CacheableMessageFormatter:
        decorates: RM\Standard\Message\Format\MessageFormatterInterface

    RM\Standard\Message\Format\JsonMessageFormatter: null
