name: PHPUnit

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  test:
    name: Testing on PHP ${{ matrix.php-versions }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.1', '8.2']

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        ini-values: opcache.jit_buffer_size=256M, opcache.jit=1235, pcre.jit=1
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
            ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test

    - uses: actions/upload-artifact@v1
      with:
        name: Coverage report
        path: coverage
