name: Security

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.0
